############app.yaml#############
###Michael Ennis Final Project###
#CS496 - Oregon State University#
########## 11/26/2017 ###########
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest